name: demo

sources:
  dip:
    path: input/variants_dip.vcf
    dims: [variant, sample]

  tri:
    path: input/variants_tri.vcf
    dims: [variant, sample]

  tet:
    path: input/variants_tet.vcf
    dims: [variant, sample]

  ma:
    path: input/variants_ma.vcf
    dims: [variant, sample]

  dip_gz:
    path: input/variants_dip.vcf.gz
    dims: [variant, sample]

steps:
  - name: describe
    inputs: [dip]

  - name: describe
    inputs: [tri]

  - name: describe
    inputs: [tet]

  - name: describe
    inputs: [ma]

  - name: describe
    inputs: [dip_gz]