name: select_demo

sources:
  data:
    path: input/data.csv
    dims: [sample, feature]
    labels:
      sample:  {feature: 0}
      feature: builtin

steps:
  - name: select
    inputs: [data]
    params:
      dim: feature
      labels: [age]
      output: selected

  - name: describe
    inputs: [selected]