# src/pipelines/gwas/manifest.py
"""GWAS manifest: default values and validation.

The manifest is the human-editable run contract. It is generated by
``scripts/init_task.py`` and consumed by ``scripts/run.py``. Users edit
it to change paths, thresholds, models and toggles.
"""

from __future__ import annotations

from src.core.errors import ValidationError


def default_manifest() -> dict:
    """Return the default GWAS manifest."""
    return {
        "pipeline": "gwas",
        "version": "0.1.0",
        "input": {
            "genotype": None,
            "phenotype": None,
            "covariates": None,
        },
        "qc": {
            "maf": 0.01,
            "missing": 0.10,
            "sample_missing": 0.10,
            "hwe": 1.0e-6,
        },
        "ld": {
            "prune": True,
            "r2": 0.2,
            "window": 100,
            "clump": True,
            "clump_r2": 0.5,
            "clump_window": 500,
        },
        "pca": {
            "enabled": True,
            "n_components": 10,
            "as_covariates": True,
        },
        "association": {
            "binary_model": "firth",
        },
        "correction": {
            "method": "bonferroni",
            "fdr_threshold": 0.05,
        },
        "plots": {
            "manhattan": True,
            "qq": True,
            "volcano": True,
            "forest": True,
            "maf_distribution": True,
            "pvalue_histogram": True,
            "chromosome_density": True,
            "effect_vs_maf": True,
            "pca_scatter": True,
            "pca_scree": True,
            "top_n_forest": 20,
        },
        "runtime": {
            "seed": 42,
            "device": "cpu",
        },
    }


def validate_manifest(cfg: dict) -> None:
    """Validate a manifest. Raises :class:`ValidationError` on failure."""
    if cfg.get("pipeline") != "gwas":
        raise ValidationError(
            "Manifest", "pipeline must be 'gwas'",
            f"got {cfg.get('pipeline')!r}",
        )

    inp = cfg.get("input", {})
    for key in ("genotype", "phenotype"):
        if not inp.get(key):
            raise ValidationError(
                "Manifest", f"input.{key} is required"
            )

    qc = cfg.get("qc", {})
    _check_range("qc.maf", qc.get("maf"), 0.0, 0.5)
    _check_range("qc.missing", qc.get("missing"), 0.0, 1.0)
    _check_range(
        "qc.sample_missing", qc.get("sample_missing"), 0.0, 1.0
    )
    hwe = qc.get("hwe")
    if hwe is not None:
        _check_range("qc.hwe", hwe, 0.0, 1.0, strict_low=True)

    pca = cfg.get("pca", {})
    if not isinstance(pca.get("n_components"), int) or \
            pca["n_components"] < 1:
        raise ValidationError(
            "Manifest", "pca.n_components must be a positive integer"
        )

    model = cfg.get("association", {}).get("binary_model")
    if model not in ("firth", "logit"):
        raise ValidationError(
            "Manifest", "association.binary_model must be 'firth' or 'logit'"
        )

    method = cfg.get("correction", {}).get("method")
    if method not in ("bonferroni", "fdr", None):
        raise ValidationError(
            "Manifest",
            "correction.method must be 'bonferroni', 'fdr' or null",
        )

    seed = cfg.get("runtime", {}).get("seed")
    if not isinstance(seed, int):
        raise ValidationError(
            "Manifest", "runtime.seed must be an integer"
        )


def _check_range(name, value, low, high, strict_low=False):
    """Range check with a strict lower bound option."""
    if value is None:
        raise ValidationError("Manifest", f"{name} is required")
    lo_ok = value > low if strict_low else value >= low
    if not (lo_ok and value <= high):
        raise ValidationError(
            "Manifest",
            f"{name} must be in "
            f"{'(' if strict_low else '['}{low}, {high}]",
            f"got {value}",
        )