# scripts/init_task.py
"""Generate a manifest.yaml for a task directory."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.pipelines import PIPELINES  # noqa: E402


def _infer_pipeline(task_dir: Path) -> str:
    """Infer pipeline name from the final token of the task directory."""
    return task_dir.name.split("_")[-1].lower()


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Scan a task directory and emit manifest.yaml."
    )
    ap.add_argument("--task", required=True, help="Task directory.")
    ap.add_argument(
        "--pipeline", default=None,
        help="Override the pipeline inferred from the task name.",
    )
    args = ap.parse_args()

    task_dir = Path(args.task).resolve()
    pipeline_name = args.pipeline or _infer_pipeline(task_dir)

    if pipeline_name not in PIPELINES:
        raise SystemExit(
            f"Unknown pipeline: '{pipeline_name}'. "
            f"Available: {list(PIPELINES.keys())}"
        )

    plugin = PIPELINES[pipeline_name]
    input_section = plugin.init.init_from_input_dir(task_dir)

    manifest = plugin.manifest.default_manifest()
    manifest["input"] = input_section

    out_path = task_dir / "manifest.yaml"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(_HEADER)
        yaml.safe_dump(manifest, f, sort_keys=False, allow_unicode=True)

    print(f"Manifest written: {out_path}")


_HEADER = (
    "# BioPipe task manifest — generated by scripts/init_task.py.\n"
    "# Edit paths and parameters as needed, then run:\n"
    "#     python scripts/run.py --task <this-directory>\n"
    "#\n"
    "# Column-name contracts for tabular inputs are fixed; see\n"
    "# docs/input_spec.md before renaming columns.\n\n"
)


if __name__ == "__main__":
    main()